export interface StudyQuote {
  id: string
  text: string
  author: string
}

export const STUDY_QUOTES: StudyQuote[] = 
[
  { id: 'q1', text: 'Nós somos o que fazemos repetidamente. Excelência não é um ato, é um hábito.', author: 'Aristóteles' },
  { id: 'q2', text: 'O sucesso é a soma de pequenos esforços repetidos dia após dia.', author: 'Robert Collier' },
  { id: 'q3', text: 'A persistência é o caminho do êxito.', author: 'Charles Chaplin' },
  { id: 'q4', text: 'A educação é a arma mais poderosa que você pode usar para mudar o mundo.', author: 'Nelson Mandela' },
  { id: 'q5', text: 'O aprendizado nunca cansa a mente.', author: 'Leonardo da Vinci' },
  { id: 'q6', text: 'Disciplina é escolher entre o que você quer agora e o que você quer mais.', author: 'Abraham Lincoln' },
  { id: 'q7', text: 'A motivação te faz começar, o hábito te faz continuar.', author: 'Jim Ryun' },
  { id: 'q8', text: 'Quem tem um porquê enfrenta quase qualquer como.', author: 'Friedrich Nietzsche' },
  { id: 'q9', text: 'Aprender é um tesouro que seguirá seu dono em qualquer lugar.', author: 'Provérbio Chinês' },
  { id: 'q10', text: 'A disciplina é a ponte entre metas e realizações.', author: 'Jim Rohn' },

  { id: 'q11', text: 'O segredo de progredir é começar.', author: 'Mark Twain' },
  { id: 'q12', text: 'Foque em ser produtivo, não apenas ocupado.', author: 'Tim Ferriss' },
  { id: 'q13', text: 'O futuro depende do que você faz hoje.', author: 'Mahatma Gandhi' },
  { id: 'q14', text: 'Sem esforço não há progresso.', author: 'Frederick Douglass' },
  { id: 'q15', text: 'A constância torna o difícil possível.', author: 'Johann Wolfgang von Goethe' },
  { id: 'q16', text: 'A repetição é a mãe do aprendizado.', author: 'John Locke' },
  { id: 'q17', text: 'A mente que se abre a uma nova ideia jamais volta ao tamanho original.', author: 'Albert Einstein' },
  { id: 'q18', text: 'O sucesso costuma vir para quem está ocupado demais para procurá-lo.', author: 'Henry David Thoreau' },
  { id: 'q19', text: 'A melhor forma de prever o futuro é criá-lo.', author: 'Peter Drucker' },
  { id: 'q20', text: 'A disciplina constrói a liberdade.', author: 'Jocko Willink' },

  { id: 'q21', text: 'Aprender é descobrir aquilo que você já sabe.', author: 'Richard Bach' },
  { id: 'q22', text: 'Nada no mundo substitui a persistência.', author: 'Calvin Coolidge' },
  { id: 'q23', text: 'A excelência não é um evento, é um processo.', author: 'Colin Powell' },
  { id: 'q24', text: 'Grandes coisas são feitas por uma série de pequenas coisas reunidas.', author: 'Vincent van Gogh' },
  { id: 'q25', text: 'A disciplina vence a motivação quando o cansaço aparece.', author: 'Jocko Willink' },
  { id: 'q26', text: 'Você não aprende a andar seguindo regras. Aprende fazendo.', author: 'Richard Branson' },
  { id: 'q27', text: 'A ação é a chave fundamental para todo sucesso.', author: 'Pablo Picasso' },
  { id: 'q28', text: 'O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.', author: 'Winston Churchill' },
  { id: 'q29', text: 'A força não vem da capacidade física, mas da vontade indomável.', author: 'Mahatma Gandhi' },
  { id: 'q30', text: 'A persistência realiza o impossível.', author: 'Provérbio Japonês' },

  { id: 'q31', text: 'O aprendizado é um processo que nunca termina.', author: 'Isaac Asimov' },
  { id: 'q32', text: 'Pequenos progressos diários levam a grandes resultados.', author: 'Robin Sharma' },
  { id: 'q33', text: 'Não é sobre ter tempo, é sobre definir prioridades.', author: 'Stephen Covey' },
  { id: 'q34', text: 'A disciplina é o combustível da consistência.', author: 'Tony Robbins' },
  { id: 'q35', text: 'A constância transforma esforço em resultado.', author: 'James Clear' },
  { id: 'q36', text: 'O foco é dizer não para centenas de boas ideias.', author: 'Steve Jobs' },
  { id: 'q37', text: 'Aprender algo novo todos os dias mantém a mente jovem.', author: 'Henry Ford' },
  { id: 'q38', text: 'O sucesso é construído diariamente.', author: 'John Wooden' },
  { id: 'q39', text: 'A prática deliberada leva à excelência.', author: 'Anders Ericsson' },
  { id: 'q40', text: 'A disciplina é liberdade.', author: 'Jocko Willink' },

  { id: 'q41', text: 'Quem estuda hoje lidera amanhã.', author: 'Desconhecido' },
  { id: 'q42', text: 'A constância vence a pressa.', author: 'Desconhecido' },
  { id: 'q43', text: 'Estudar um pouco todos os dias constrói grandes resultados.', author: 'Desconhecido' },
  { id: 'q44', text: 'A rotina bem feita cria progresso silencioso.', author: 'Desconhecido' },
  { id: 'q45', text: 'O foco diário reduz a distância até a meta.', author: 'Desconhecido' },
  { id: 'q46', text: 'Persistir é continuar mesmo sem vontade.', author: 'Desconhecido' },
  { id: 'q47', text: 'O estudo consistente elimina a improvisação.', author: 'Desconhecido' },
  { id: 'q48', text: 'A disciplina diária constrói confiança.', author: 'Desconhecido' },
  { id: 'q49', text: 'Aprender é avançar mesmo quando ninguém vê.', author: 'Desconhecido' },
  { id: 'q50', text: 'Metas claras tornam o estudo mais leve.', author: 'Desconhecido' },

  { id: 'q51', text: 'A repetição transforma dificuldade em domínio.', author: 'Bruce Lee' },
  { id: 'q52', text: 'O sucesso começa com autodisciplina.', author: 'Napoleon Hill' },
  { id: 'q53', text: 'Você se torna aquilo que pratica diariamente.', author: 'John Maxwell' },
  { id: 'q54', text: 'Aprender é o único investimento que nunca perde valor.', author: 'Benjamin Franklin' },
  { id: 'q55', text: 'A disciplina cria resultados previsíveis.', author: 'Peter Drucker' },
  { id: 'q56', text: 'O foco constrói profundidade.', author: 'Cal Newport' },
  { id: 'q57', text: 'A excelência nasce da repetição consciente.', author: 'Will Durant' },
  { id: 'q58', text: 'O estudo contínuo sustenta o crescimento.', author: 'Carol Dweck' },
  { id: 'q59', text: 'A persistência é mais poderosa que o talento.', author: 'Angela Duckworth' },
  { id: 'q60', text: 'A disciplina diária constrói liberdade futura.', author: 'Jordan Peterson' },

  { id: 'q61', text: 'Aprender exige esforço, mas recompensa com autonomia.', author: 'Paulo Freire' },
  { id: 'q62', text: 'O hábito certo no dia certo muda tudo.', author: 'BJ Fogg' },
  { id: 'q63', text: 'A consistência é a base da maestria.', author: 'Robin Sharma' },
  { id: 'q64', text: 'O foco prolongado gera resultados profundos.', author: 'Daniel Goleman' },
  { id: 'q65', text: 'A disciplina sustenta o progresso.', author: 'James Clear' },
  { id: 'q66', text: 'Estudar é um ato de responsabilidade consigo mesmo.', author: 'Paulo Freire' },
  { id: 'q67', text: 'A prática constante vence a inspiração ocasional.', author: 'Seth Godin' },
  { id: 'q68', text: 'O aprendizado é construído em camadas.', author: 'Salman Khan' },
  { id: 'q69', text: 'A disciplina transforma intenção em resultado.', author: 'Brian Tracy' },
  { id: 'q70', text: 'A clareza da meta sustenta o foco.', author: 'Tony Robbins' },

  { id: 'q71', text: 'O progresso real nasce da constância.', author: 'Desconhecido' },
  { id: 'q72', text: 'Estudar todos os dias reduz o esforço futuro.', author: 'Desconhecido' },
  { id: 'q73', text: 'A disciplina vence a procrastinação.', author: 'Desconhecido' },
  { id: 'q74', text: 'Pequenos hábitos constroem grandes vitórias.', author: 'Desconhecido' },
  { id: 'q75', text: 'A rotina certa cria resultados duradouros.', author: 'Desconhecido' },
  { id: 'q76', text: 'Persistir é manter o ritmo.', author: 'Desconhecido' },
  { id: 'q77', text: 'O estudo diário cria segurança.', author: 'Desconhecido' },
  { id: 'q78', text: 'A disciplina organiza o progresso.', author: 'Desconhecido' },
  { id: 'q79', text: 'O foco protege seu tempo.', author: 'Desconhecido' },
  { id: 'q80', text: 'Aprender constantemente reduz incertezas.', author: 'Desconhecido' },

  { id: 'q81', text: 'O sucesso é construído um dia de cada vez.', author: 'Desconhecido' },
  { id: 'q82', text: 'A constância elimina a pressa.', author: 'Desconhecido' },
  { id: 'q83', text: 'Estudar com regularidade cria domínio.', author: 'Desconhecido' },
  { id: 'q84', text: 'A disciplina diária constrói estabilidade.', author: 'Desconhecido' },
  { id: 'q85', text: 'O foco transforma esforço em progresso.', author: 'Desconhecido' },
  { id: 'q86', text: 'Persistência é não desistir do básico.', author: 'Desconhecido' },
  { id: 'q87', text: 'Aprender é avançar com consistência.', author: 'Desconhecido' },
  { id: 'q88', text: 'A rotina cria resultados silenciosos.', author: 'Desconhecido' },
  { id: 'q89', text: 'Disciplina é respeitar suas próprias metas.', author: 'Desconhecido' },
  { id: 'q90', text: 'O estudo contínuo constrói confiança.', author: 'Desconhecido' },

  { id: 'q91', text: 'A repetição diária gera excelência.', author: 'Desconhecido' },
  { id: 'q92', text: 'A disciplina mantém o progresso ativo.', author: 'Desconhecido' },
  { id: 'q93', text: 'O foco reduz a distância até o objetivo.', author: 'Desconhecido' },
  { id: 'q94', text: 'Estudar hoje evita arrependimentos.', author: 'Desconhecido' },
  { id: 'q95', text: 'A constância constrói liberdade futura.', author: 'Desconhecido' },
  { id: 'q96', text: 'Persistir é continuar aprendendo.', author: 'Desconhecido' },
  { id: 'q97', text: 'A disciplina diária constrói resultados reais.', author: 'Desconhecido' },
  { id: 'q98', text: 'O foco organiza o esforço.', author: 'Desconhecido' },
  { id: 'q99', text: 'Aprender todos os dias fortalece a mente.', author: 'Desconhecido' },
  { id: 'q100', text: 'O progresso nasce da constância.', author: 'Desconhecido' }
]